easy_admin:
    entities:
      Page:
        class: App\Entity\Page

      User:
        class: App\Entity\User
        form:
          fields:
            - username
            - { property: 'roles', type: 'textbox' }
            - email
            - first_name
            - last_name
            - { property: 'password', type: 'password' }
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
    user:
        name_property_path: "username"