home:
    path: /
    controller: App\Controller\HomeController::index

contacts:
    path: /contacts/
    controller: App\Controller\ContactsController::index

login:
    path: /login/
    controller: App\Controller\AuthController::login

logout:
    path: /logout/
    controller: App\Controller\AuthController::logout
